# Generated by Django 4.2.3 on 2023-08-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_passwordresetcodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
